### ISSUE TITLE
codec can't encode character '\u200d' when running prep_apks.py

### ISSUE THREAD

**Issue by rcmpayne** [nshuba/download_apks#2]
$ python prep_apks.py <bla> <bla>. apps.csv

```
Fetching apps for category EVENTS
        com.showhd.hdcinema
        com.zombie.addons.mods.mutant.vampire.pe
        com.topRingtones.TikTok
        com.gametime.gametime
        com.greetingsisland.sam
        com.survival.maps.redstone
        com.pets.mods.addons.animal
        com.vrchat.anime.avatars.online
        jmayyy.nnjja
Traceback (most recent call last):
  File "prep_apks.py", line 111, in <module>
    prep_app_list(server, args.apps_csv)
  File "prep_apks.py", line 66, in prep_app_list
    writer.writerow(row)
  File "C:\Users\rpayne\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u200d' in position 26: character maps to <undefined>
```

**Comment by nshuba** [comment]
Hmm, I am having a hard time reproducing. The "jmayyy.nnjja" app went through fine for me. Can you try again please? Perhaps it was a temporary Google Play error?
